services:
  producer:
    image: producer
    build:
      context: ./cmd/producer
    container_name: producer
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - prometheus
      - pushgateway

  consumer:
    image: consumer
    build:
      context: ./cmd/consumer
    container_name: consumer
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - prometheus
      - pushgateway

  invoice:
    image: invoice
    build:
      context: ./cmd/invoice
    container_name: invoice
    ports:
      - "8000:8000"
    volumes:
      - "D:/Workspace/data:/app/data"
    depends_on:
      - rabbitmq
      - redis
      - prometheus
      - pushgateway

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
