services:
  producer:
    image: producer
    build:
      context: .
      dockerfile: cmd/producer/Dockerfile
    container_name: producer
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - prometheus

  consumer:
    image: consumer
    build:
      context: .
      dockerfile: cmd/consumer/Dockerfile
    container_name: consumer
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - prometheus

  invoice:
    image: invoice
    build:
      context: ./cmd/invoice
    container_name: invoice
    ports:
      - "8000:8000"
    volumes:
      - "./data:/app/data"
    depends_on:
      - rabbitmq
      - redis
      - prometheus

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
